### ISSUE TITLE
Maps don't appear in any browser since Thursday 10th of November 2016. 

### ISSUE THREAD

**Issue by ioannapsygkacch** [PublicaMundi/geodata.gov.gr#2]

**Comment by kalxas** [comment]
Hi @ioannapsygkacch and thank you for your report.
Can you please specify if this issue is on the "Maps" section or in the preview map of a dataset?

**Comment by ioannapsygkacch** [comment]
Hello Angele,

Many thanks for your prompt response. The problem is on the “Maps” section. As soon as I click on the “Maps” tab, no map appears. The rest of the page looks okay (i.e. the bar on the left of the page).

BR,
Ioanna

[H&S e-mail signature 1]

Ioanna Psygka
Supply Chain Graduate Trainee

60, Kifisias Avenue, 15125,
Athens, Greece
M: +30 6975823069
E-mail: ioanna.psygka@cchellenic.commailto:ioanna.psygka@cchellenic.com
www.coca-colahellenic.grhttp://www.coca-colahellenic.gr/
                                                      [social] http://www.facebook.com/CocaCola3E

**Comment by kalxas** [comment]
@ioannapsygkacch we have had some issues with our NFS backends, which caused this outage of map tiles.
We have now restored the problem, can you please confirm that this is fixed for you now?
Thanks,
Angelos

**Comment by ioannapsygkacch** [comment]
Hello again,

I just checked and it’s working properly now.

Thank you very much for your help and cooperation.

Best Regards,
[H&S e-mail signature 1]

Ioanna Psygka
Supply Chain Graduate Trainee

60, Kifisias Avenue, 15125,
Athens, Greece
M: +30 6975823069
E-mail: ioanna.psygka@cchellenic.commailto:ioanna.psygka@cchellenic.com
www.coca-colahellenic.grhttp://www.coca-colahellenic.gr/
                                                      [social] http://www.facebook.com/CocaCola3E
