### ISSUE TITLE
ελληνικοι χαρακτηρες shp

### ISSUE THREAD

**Issue by koupali1** [PublicaMundi/geodata.gov.gr#3]
όταν κατεβάζουμε τα shapefile, οι ελληνικοί χαρακτήρες στο attribute table δεν διαβάζονται. Είναι σύμβολα ή ερωτηματικά. Γνωρίζετε τρόπο να ξεπεραστεί το πρόβλημα;;

ευχαριστώ

**Comment by kalxas** [comment]
Με ποιό λογισμικό δοκιμάζετε να ανοίξετε τα shapefiles ;

**Comment by koupali1** [comment]
arcgis


________________________________

**Comment by kalxas** [comment]
Το πρόβλημά αυτό οφείλεται στις ρυθμίσεις κωδικοποίησης των Ελληνικών. Τα περισσότερα δεδομένα που παρέχουμε είναι σε κωδικοποίηση UTF-8 και ορισμένα σε κωδικοποίηση Windows-1253 ή CP-1253.
Δοκιμάστε να αλλάξετε την κωδικοποίηση του συστήματός σας και τα δεδομένα θα φανούν σωστά.

**Comment by koupali1** [comment]
ευχαριστω


________________________________
